apiVersion: apps/v1
kind: Deployment
metadata:
  name: waves-demo-deployment
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waves-demo
  template:
    metadata:
      labels:
        app: waves-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: waves-demo-config
              key: APP_MESSAGE
