apiVersion: v1
kind: Service
metadata:
  name: waves-demo-service
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: NodePort
  selector:
    app: waves-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30090
